
name: Build Android APK

on:
  workflow_dispatch:

jobs:
  apk:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Build Android APK
        run: |
          docker run --rm \
            -v "$PWD":/home/user/hostcwd \
            ghcr.io/kivy/buildozer:latest \
            android debug --sdk-accept-licenses

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CryptoAlert-APK
          path: bin/*.apk
          if-no-files-found: error
